### ISSUE TITLE
[FEAT] How can I use this code to do correct syntax highlighting in Markdown?

### ISSUE THREAD

**Issue by dmccreary** [DavidBakerEffendi/vsc-gsql-extension#6]
Jon Herke suggested I ping you.  We are trying to publish documentation on GSQL in Markdown (with mkdocs).

Can you let me know if your code might be used to do this also?

Jon also point me to this site: https://pygments.org/

**Comment by DavidBakerEffendi** [comment]
Haven't tried - VS Code, Sublime, etc. use the same input format when creating a semantic highlighting plugin since they're both powered by TextMate. An example of this is in [gsql.tmLanguage.json](https://github.com/DavidBakerEffendi/vsc-gsql-extension/blob/master/syntaxes/gsql.tmLanguage.json). 

If something like MkDocs uses TextMate to support syntax highlighting then you can simply plugin `gsql.tmLanguage.json` to extend it. Otherwise, since `gsql.tmLanguage.json` contains all the regexes you could transcribe them in a format in which the markdown engine will recognize.
